//
//  OnboardingView.swift
//  GPTDetectorSwiftUI
//
//  Created by cem on 27.08.2023.
//

import SwiftUI

struct OnboardingView: View {
    @StateObject private var onboardingViewModel = OnboardingViewModel(cacheClient: CacheClient())
    @Binding var isOnboardingCompleted: Bool

    var body: some View {
        ZStack {
            Color.theme.backgroundColor
                .ignoresSafeArea()
            VStack(alignment: .leading, spacing: .spacing.veryHigh) {
                HStack {
                    Spacer()
                    ZStack(alignment: .bottom) {
                        Image("LaunchScreen")
                            .resizable()
                            .scaledToFit()
                            .frame(width: 150, height: 150)
                        Text("GPT Detector")
                            .font(.title)
                    }
                    Spacer()
                }
                Group {
                    HStack(spacing: .spacing.veryHigh) {
                        Image(systemName: "hand.wave")
                            .resizable()
                            .scaledToFit()
                            .frame(width: 40, height: 40)
                            .foregroundColor(Color.theme.accentColor)

                        Text("Welcome to GPT Detector! GPT Detector whether a given text has been generated by a large language model or not.")
                        Spacer()
                    }
                    HStack(spacing: .spacing.veryHigh) {
                        Image(systemName: "character.bubble")
                            .resizable()
                            .scaledToFit()
                            .frame(width: 40, height: 40)
                            .foregroundColor(Color.theme.accentColor)

                        Text("For the best results, we highly recommend using English text.")
                        Spacer()
                    }
                }
                .padding(.horizontal)

                Spacer()
                Button {
                    onboardingViewModel.completeOnboarding()
                    isOnboardingCompleted = true
                } label: {
                    Text("Get Started")
                        .frame(maxWidth: .infinity, minHeight: .buttonSize.regular)
                        .background(Color.theme.accentColor)
                        .foregroundColor(Color.theme.secondaryTextColor)
                        .font(.headline)
                        .cornerRadius(.borderRadius.regular)
                }
            }
            .padding()
        }
    }
}

struct OnboardingView_Previews: PreviewProvider {
    static var previews: some View {
        NavigationStack {
            OnboardingView(isOnboardingCompleted: .constant(false))
        }
    }
}
